# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.12.2
forge_version=14.23.5.2860

mappings_channel=stable
mappings_version=39-1.12

mod_maven_group=dev.arisu.gtcedyntree
mod_id=gtcedyntree
mod_version=1.0.2
mod_jar_name=GTNEDynTree
mod_name=GregTech Nomifactory Edition
mod_author=happysmash27
mod_description=Adds compatibility between dynamic trees and GregTech Nomifactory Edition
mod_url=https://github.com/happysmash27/GTCEDynTree
mod_update_url=https://github.com/happysmash27/GTCEDynTree/blob/master/update.json?raw=true

deps_gregtechne_version=1.18.6
deps_gregtechne_curse_ref=1019238:6309288

deps_dynamictrees_version=1.12.2:0.9.27

deps_hwyla_version=1.8.26-B41_1.12.2
deps_hwyla_curse_ref=253449:2568751

deps_jei_version=1.12.2:4.15.0.293
deps_ccl_version=1.12.2-3.2.3.358
